### ISSUE TITLE
loss_func is  not defined

### ISSUE THREAD

**Issue by Navee402** [shigen-StoneRoot/FFPN#1]
Hi, this is such an amazing work. I have cloned it to my system and tried to run the same on IXI dataset. However I figured out that the loss_func in main_pretraining.py has not been defined anywhere. also the variable regression_tar is not defined, Can you please suggest me what kind of loss function have you been using so that I will try to reproduce it and see the results.  Thank you!

**Comment by shigen-StoneRoot** [comment]
Hi,
Thanks for your interest in our work. The loss_func should be:
```
loss_func = DiceCELoss(to_onehot_y=True, softmax=True,
                           squared_pred=True, smooth_nr=0.0, smooth_dr=1e-6)
```
and we should import this:
```
from monai.losses import DiceCELoss
```
The manuscript has been rejected a few times, and this is the initial code, so there may be some errors. 

I have made some changes to fix the errors (please update the main_pretraining.py file), and I hope it can run well.
